### ISSUE TITLE
See Also

### ISSUE THREAD

**Issue by ronsavage** [perlancar/perl-Bencher-Scenario-SetOperationModules#1]
Hi

I'm suprised by this module, but nevertheless, please add
https://metacpan.org/pod/Benchmark::Featureset::SetOps
to See Also.

**Comment by perlancar** [comment]
Hi Ron, 

I didn't search for any prior art when creating Bencher::Scenario::SetOperationModules (in recent weeks I have been creating a bunch of Bencher::Scenario::\* modules to exercise my Bencher framework).

Anyhow, I took a look at your module, which is quite cool. I particularly enjoyed the report. Apparently, the module is more than just about benchmarking performance, but also comparison of various aspects (reminds of me Neil Bowers' CPAN Module Reviews series [1]). Have you considered putting the module in something other than the Benchmark:: namespace (like, say, Module::Compare, or Acme::Module::Compare or something)?

As per your request, I've added Benchmark::Featureset::SetOps to See Also. I'll also add some of the modules reviewed in your module to my benchmarks.

Regards,

[1] http://neilb.org/reviews/

**Comment by ronsavage** [comment]
Hi

On 19/11/15 00:44, perlancar wrote:

> Hi Ron,
> 
> I didn't search for any prior art when creating
> Bencher::Scenario::SetOperationModules (in recent weeks I have been
> creating a bunch of Bencher::Scenario::\* modules to exercise my Bencher
> framework).

No problem.

> Anyhow, I took a look at your module, which is quite cool. I

Thanx.

> particularly enjoyed the report. Apparently, the module is more than
> just about benchmarking performance, but also comparison of various
> aspects (reminds of me Neil Bowers' CPAN Module Reviews series [1]).

I keep track of reviews at http://savage.net.au/Module-reviews.html, so 
I'll add you work to that.

> Have you considered putting the module in something other than the
> Benchmark:: namespace (like, say, Module::Compare, or
> Acme::Module::Compare or something)?

I had a long think about the naming of these modules (there are 3 in the 
set so far), and it was difficult to choose something suitable. But I 
think Benchmark::\* does the job, although I guess some people would 
assume it's about speed tests.

> As per your request, I've added Benchmark::Featureset::SetOps to See
> Also. I'll also add some of the modules reviewed in your module to my
> benchmarks.

Thanx.

> Regards,
> 
> [1] http://neilb.org/reviews/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/perlancar/perl-Bencher-Scenario-SetOperationModules/issues/1#issuecomment-157717174.

## 

Ron Savage - savage.net.au
